import type { ReactNode } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';

import type { ExpenseCategory } from '../api/types';
import { categorySegments, type Period } from '../finance/presentation';
import { colors, radii, shadows, spacing } from '../theme/tokens';
import { Money } from '../ui';
import { Icon, type IconName } from './Icon';

export function AppHeader({ title = 'Monetra', action, onAction }: { title?: string; action?: IconName; onAction?: () => void }) {
  return <View style={styles.header}><View style={styles.brand}><Image source={require('../../assets/monetra-app-icon.png')} accessibilityLabel="Monetra" style={styles.brandMark} /><Text style={styles.brandName}>{title}</Text></View>{action && onAction ? <Pressable accessibilityRole="button" onPress={onAction} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><Icon name={action} /></Pressable> : null}</View>;
}

export function PeriodSwitcher({ period, onChange }: { period: Period; onChange: (direction: -1 | 1) => void }) {
  const label = new Intl.DateTimeFormat('es-CL', { month: 'long', year: 'numeric' }).format(new Date(period.year, period.month - 1, 1));
  return <View style={styles.period}><Pressable accessibilityLabel="Mes anterior" onPress={() => onChange(-1)} style={({ pressed }) => [styles.periodButton, pressed && styles.pressed]}><Icon name="chevron-left" size={18} /></Pressable><View style={styles.periodLabel}><Icon name="calendar" size={16} color={colors.muted} /><Text style={styles.periodText}>{label.charAt(0).toUpperCase() + label.slice(1)}</Text></View><Pressable accessibilityLabel="Mes siguiente" onPress={() => onChange(1)} style={({ pressed }) => [styles.periodButton, pressed && styles.pressed]}><Icon name="chevron-right" size={18} /></Pressable></View>;
}

export function BalanceCard({ balance, income, expense, symbol }: { balance: number; income: number; expense: number; symbol: string }) {
  return <View style={styles.balanceCard}><View style={styles.balanceTop}><View><Text style={styles.balanceLabel}>Balance del mes</Text><Money value={balance} symbol={symbol} inverse /></View><View style={styles.balancePill}><Icon name={balance >= 0 ? 'income' : 'expense'} size={13} color="#d9f6df" /><Text style={styles.balancePillText}>{balance >= 0 ? 'En positivo' : 'Por revisar'}</Text></View></View><View style={styles.balanceMeta}><BalanceMeta label="Ingresos" value={income} symbol={symbol} /><BalanceMeta label="Gastos" value={expense} symbol={symbol} align="right" /></View></View>;
}

function BalanceMeta({ label, value, symbol, align }: { label: string; value: number; symbol: string; align?: 'right' }) { return <View style={align ? { alignItems: 'flex-end' } : undefined}><Text style={styles.balanceMetaLabel}>{label}</Text><Text style={styles.balanceMetaValue}>{symbol}{value.toLocaleString('es-CL')}</Text></View>; }

export function SectionHeader({ title, actionLabel, onAction }: { title: string; actionLabel?: string; onAction?: () => void }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{actionLabel && onAction ? <Pressable onPress={onAction}><Text style={styles.link}>{actionLabel}</Text></Pressable> : null}</View>; }

export function MetricCard({ icon, label, value, caption, tone, symbol }: { icon: IconName; label: string; value: number; caption: string; tone: 'income' | 'expense'; symbol: string }) { const accent = tone === 'income' ? colors.success : colors.warning; return <View style={styles.metricCard}><View style={[styles.metricIcon, { backgroundColor: tone === 'income' ? '#e8faf0' : '#fff1ed' }]}><Icon name={icon} color={accent} size={18} /></View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{symbol}{value.toLocaleString('es-CL')}</Text><Text style={[styles.metricCaption, { color: accent }]}>{caption}</Text></View>; }

export function BudgetCard({ limit, spent, remaining, usedPct, daysRemaining, symbol }: { limit: number; spent: number; remaining: number; usedPct: number | null; daysRemaining: number; symbol: string }) { const percent = Math.min(Math.max(usedPct ?? 0, 0), 100); return <View style={styles.budgetCard}><View style={styles.budgetLine}><View><Text style={styles.budgetCaption}>Límite mensual</Text><Text style={styles.budgetValue}>{symbol}{limit.toLocaleString('es-CL')}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={styles.budgetCaption}>Disponible</Text><Text style={styles.budgetValue}>{symbol}{remaining.toLocaleString('es-CL')}</Text></View></View><View style={styles.progressTrack}><View style={[styles.progressValue, { width: `${percent}%`, backgroundColor: percent >= 100 ? colors.danger : colors.accent }]} /></View><View style={styles.budgetLine}><Text style={styles.budgetFooter}>Gastado {symbol}{spent.toLocaleString('es-CL')}</Text><Text style={styles.budgetFooter}>{daysRemaining} días restantes</Text></View></View>; }

export function DonutChart({ categories }: { categories: ExpenseCategory[] }) { const circumference = 301.6; const segments = categorySegments(categories); return <View style={styles.chartCard}><View style={styles.chartLayout}><View><Svg width={142} height={142} viewBox="0 0 142 142"><Circle cx="71" cy="71" r="48" fill="none" stroke="#eeeae7" strokeWidth="22" /><Circle cx="71" cy="71" r="48" fill="none" stroke={colors.background} strokeWidth="16" />{segments.map((segment, index) => <Circle key={segment.id} cx="71" cy="71" r="48" fill="none" stroke={categories[index]?.color ?? colors.meta} strokeWidth="22" strokeDasharray={`${segment.percent / 100 * circumference} ${circumference}`} strokeDashoffset={-segment.offset / 100 * circumference} rotation="-90" origin="71,71" />)}</Svg></View><View style={styles.legend}>{categories.slice(0, 4).map((category) => <View key={category.id} style={styles.legendRow}><View style={[styles.legendDot, { backgroundColor: category.color }]} /><Text numberOfLines={1} style={styles.legendLabel}>{category.name}</Text><Text style={styles.legendValue}>{Math.round(category.percentage)}%</Text></View>)}</View></View></View>; }

export function PrimaryButton({ children, onPress, icon, loading, variant = 'primary' }: { children: ReactNode; onPress: () => void; icon?: IconName; loading?: boolean; variant?: 'primary' | 'secondary' | 'danger' }) { const backgroundColor = variant === 'primary' ? colors.accent : variant === 'danger' ? '#fff0f0' : colors.surface; const textColor = variant === 'primary' ? colors.onAccent : variant === 'danger' ? colors.danger : colors.text; return <Pressable disabled={loading} onPress={onPress} style={({ pressed }) => [styles.primaryButton, { backgroundColor, opacity: loading ? .65 : 1 }, pressed && !loading && styles.pressed]}>{icon ? <Icon name={icon} size={18} color={textColor} /> : null}<Text style={[styles.primaryText, { color: textColor }]}>{loading ? 'Guardando…' : children}</Text></Pressable>; }

export function EmptyState({ title, copy, action }: { title: string; copy: string; action?: ReactNode }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyCopy}>{copy}</Text>{action}</View>; }

export function ErrorState({ title = 'No pudimos cargar esta información', onRetry }: { title?: string; onRetry: () => void }) {
  return <EmptyState title={title} copy="Revisa tu conexión e inténtalo nuevamente." action={<View style={{ width: '100%', marginTop: spacing.sm }}><PrimaryButton onPress={onRetry}>Reintentar</PrimaryButton></View>} />;
}

const styles = StyleSheet.create({
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm }, brand: { flexDirection: 'row', alignItems: 'center', gap: 10 }, brandMark: { width: 34, height: 34 }, brandName: { fontSize: 18, fontWeight: '800', color: colors.text }, iconButton: { width: 44, height: 44, borderWidth: 1, borderColor: colors.border, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center' }, pressed: { opacity: .82, transform: [{ scale: .97 }] },
  period: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: spacing.sm }, periodButton: { width: 32, height: 32, backgroundColor: colors.background, borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, periodLabel: { flexDirection: 'row', alignItems: 'center', gap: 7 }, periodText: { color: colors.text, fontWeight: '700', fontSize: 14 },
  balanceCard: { padding: 18, backgroundColor: colors.text, borderRadius: radii.lg, marginTop: 14, shadowColor: colors.text, shadowOffset: { width: 0, height: 14 }, shadowOpacity: .16, shadowRadius: 28, elevation: 5 }, balanceTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, balanceLabel: { color: 'rgba(255,255,255,.72)', fontSize: 13 }, balancePill: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 5, paddingHorizontal: 8, borderRadius: radii.pill, backgroundColor: 'rgba(255,255,255,.12)', alignSelf: 'flex-start' }, balancePillText: { color: '#d9f6df', fontSize: 11, fontWeight: '700' }, balanceMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, paddingTop: 13, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.14)' }, balanceMetaLabel: { color: 'rgba(255,255,255,.62)', fontSize: 11 }, balanceMetaValue: { color: colors.onAccent, marginTop: 3, fontWeight: '700', fontSize: 14 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 }, sectionTitle: { fontSize: 18, fontWeight: '800', color: colors.text }, link: { color: colors.accent, fontWeight: '700', fontSize: 12 }, metricCard: { flex: 1, minHeight: 116, padding: 14, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, ...shadows.card }, metricIcon: { width: 28, height: 28, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' }, metricLabel: { marginTop: 10, color: colors.muted, fontSize: 12 }, metricValue: { marginTop: 3, color: colors.text, fontWeight: '800', fontSize: 18 }, metricCaption: { marginTop: 5, fontSize: 11, fontWeight: '700' },
  budgetCard: { padding: spacing.md, backgroundColor: colors.surface, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border }, budgetLine: { flexDirection: 'row', justifyContent: 'space-between' }, budgetCaption: { color: colors.muted, fontSize: 12 }, budgetValue: { marginTop: 3, color: colors.text, fontWeight: '700', fontSize: 15 }, progressTrack: { height: 8, overflow: 'hidden', borderRadius: radii.pill, backgroundColor: '#e2dfdc', marginVertical: 13 }, progressValue: { height: '100%', borderRadius: radii.pill }, budgetFooter: { color: colors.muted, fontSize: 11 },
  chartCard: { padding: spacing.md, borderRadius: radii.lg, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, ...shadows.card }, chartLayout: { flexDirection: 'row', alignItems: 'center', gap: 14 }, legend: { flex: 1, gap: 10 }, legendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, legendDot: { width: 9, height: 9, borderRadius: radii.pill }, legendLabel: { flex: 1, color: colors.muted, fontSize: 12 }, legendValue: { color: colors.text, fontSize: 12, fontWeight: '700' },
  primaryButton: { minHeight: 46, paddingHorizontal: 14, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7, borderRadius: radii.md }, primaryText: { fontSize: 14, fontWeight: '800' }, empty: { padding: spacing.xl, alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, backgroundColor: colors.surface }, emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 16 }, emptyCopy: { color: colors.muted, textAlign: 'center', lineHeight: 20 },
});
