import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api/client';
import type { Goal } from '../../src/api/types';
import { Loading, Screen } from '../../src/ui';
import { colors, radii, spacing } from '../../src/theme/tokens';
import { useSession } from '../../src/auth/session';
import { AppHeader, EmptyState, ErrorState, PrimaryButton } from '../../src/components/FinanceUi';
import { Icon } from '../../src/components/Icon';
import { confirmDeleteGoal, ContributionEditor, GoalEditor } from '../../src/features/goals/GoalEditor';
import { useGoalMutations } from '../../src/features/goals/useGoalMutations';

export default function GoalsScreen() {
  const { user } = useSession(); const [editor, setEditor] = useState(false); const [contribution, setContribution] = useState(false); const [selected, setSelected] = useState<Goal | null>(null); const mutations = useGoalMutations(); const query = useQuery({ queryKey: ['goals'], queryFn: async () => (await api.get<Goal[]>('/savings?completed=false')).data });
  if (query.isLoading) return <Loading />;
  const openNew = () => { setSelected(null); setEditor(true); }; const remove = (id: number) => confirmDeleteGoal(() => void mutations.remove.mutateAsync(id).catch((error) => Alert.alert('No pudimos eliminarla', error instanceof Error ? error.message : 'Inténtalo nuevamente.')));
  return <Screen refreshing={query.isFetching} onRefresh={() => void query.refetch()}>{query.isError ? <><AppHeader /><ErrorState title="No pudimos cargar tus metas" onRetry={() => void query.refetch()} /></> : <><AppHeader action="plus" onAction={openNew} /><View style={styles.head}><View style={styles.headCopy}><Text style={styles.eyebrow}>Plan de ahorro</Text><Text style={styles.title}>Metas</Text><Text style={styles.copy}>Convierte tus objetivos en avances concretos.</Text></View><Pressable onPress={openNew} style={styles.add}><Icon name="plus" color={colors.onAccent} /></Pressable></View>{query.data?.length ? query.data.map((goal) => <View key={goal.id} style={styles.card}><View style={styles.goalHeader}><View style={[styles.goalIcon, { backgroundColor: goal.is_completed ? '#e8faf0' : colors.surfaceBlue }]}><Icon name="target" color={goal.is_completed ? colors.success : colors.accent} /></View><View style={{ flex: 1, minWidth: 0 }}><Text numberOfLines={1} style={styles.goalName}>{goal.name}</Text><Text numberOfLines={1} style={styles.goalDate}>{goal.target_date ? `Meta: ${goal.target_date}` : 'Sin fecha objetivo'}</Text></View><Pressable onPress={() => { setSelected(goal); setEditor(true); }}><Icon name="edit" color={colors.muted} size={18} /></Pressable></View><Text style={styles.goalAmount}>{user?.currency_symbol ?? '$'}{goal.current_amount.toLocaleString('es-CL')} <Text style={styles.goalOf}>de {user?.currency_symbol ?? '$'}{goal.target_amount.toLocaleString('es-CL')}</Text></Text><View style={styles.track}><View style={[styles.value, { width: `${Math.min(goal.progress_pct, 100)}%`, backgroundColor: goal.is_completed ? colors.success : colors.accent }]} /></View><View style={styles.footer}><Text style={styles.progress}>{goal.progress_pct.toFixed(0)}% · faltan {user?.currency_symbol ?? '$'}{goal.remaining.toLocaleString('es-CL')}</Text><View style={styles.actions}><Pressable onPress={() => { setSelected(goal); setContribution(true); }}><Text style={styles.contribute}>Abonar</Text></Pressable><Pressable onPress={() => remove(goal.id)}><Icon name="trash" size={18} color={colors.danger} /></Pressable></View></View></View>) : <EmptyState title="Aún no tienes metas" copy="Crea una meta y sigue cada avance desde aquí." action={<View style={{ width: '100%', marginTop: spacing.sm }}><PrimaryButton onPress={openNew} icon="plus">Crear meta</PrimaryButton></View>} />}</>}<GoalEditor visible={editor} goal={selected} onClose={() => setEditor(false)} /><ContributionEditor visible={contribution} goal={selected} onClose={() => setContribution(false)} /></Screen>;
}

const styles = StyleSheet.create({ head: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md }, headCopy: { flex: 1, minWidth: 0 }, eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase' }, title: { color: colors.text, fontSize: 27, fontWeight: '800', marginTop: 4 }, copy: { color: colors.muted, marginTop: 6, lineHeight: 20 }, add: { flexShrink: 0, width: 44, height: 44, borderRadius: radii.md, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, card: { padding: spacing.md, gap: spacing.sm, borderRadius: radii.lg, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border }, goalHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 }, goalIcon: { flexShrink: 0, width: 36, height: 36, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, goalName: { color: colors.text, fontSize: 16, fontWeight: '800' }, goalDate: { color: colors.muted, fontSize: 12, marginTop: 2 }, goalAmount: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 4 }, goalOf: { color: colors.muted, fontSize: 13, fontWeight: '500' }, track: { height: 9, borderRadius: radii.pill, overflow: 'hidden', backgroundColor: colors.border }, value: { height: '100%', borderRadius: radii.pill }, footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, progress: { color: colors.muted, fontSize: 12 }, actions: { flexDirection: 'row', alignItems: 'center', gap: 14 }, contribute: { color: colors.accent, fontWeight: '800', fontSize: 13 } });
