import { useEffect, useRef, useState } from 'react';
import { Alert, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { apiError } from '../../api/client';
import type { Goal, GoalFormValues } from '../../api/types';
import { buildContributionPayload, buildGoalPayload } from '../../finance/presentation';
import { colors, radii, spacing } from '../../theme/tokens';
import { Icon } from '../../components/Icon';
import { PrimaryButton } from '../../components/FinanceUi';
import { useGoalMutations } from './useGoalMutations';
import { isCurrentEditorSubmission } from '../editorSafety';

export function GoalEditor({ visible, goal, onClose }: { visible: boolean; goal?: Goal | null; onClose: () => void }) {
  const mutations = useGoalMutations(); const insets = useSafeAreaInsets(); const editorSession = useRef(0); const visibleRef = useRef(visible); const [values, setValues] = useState<GoalFormValues>({ name: '', targetAmount: '', currentAmount: '', targetDate: '' }); const [error, setError] = useState('');
  useEffect(() => {
    visibleRef.current = visible;
    if (visible) {
      editorSession.current += 1;
      setError('');
      setValues({ name: goal?.name ?? '', targetAmount: goal ? String(goal.target_amount) : '', currentAmount: goal ? String(goal.current_amount) : '0', targetDate: goal?.target_date ?? '' });
    }
    return () => { editorSession.current += 1; visibleRef.current = false; };
  }, [visible, goal]);
  const set = <K extends keyof GoalFormValues>(key: K, value: GoalFormValues[K]) => setValues((current) => ({ ...current, [key]: value })); const saving = mutations.create.isPending || mutations.update.isPending;
  const close = () => { if (!saving) onClose(); };
  const save = async () => { if (saving) return; const payload = buildGoalPayload(values); if (!payload.name || !Number.isFinite(payload.target_amount) || payload.target_amount <= 0 || !Number.isFinite(payload.current_amount) || payload.current_amount < 0) { setError('Completa el nombre y montos válidos.'); return; } const submissionSession = editorSession.current; try { if (goal) await mutations.update.mutateAsync({ id: goal.id, payload }); else await mutations.create.mutateAsync(payload); if (isCurrentEditorSubmission(submissionSession, editorSession.current, visibleRef.current)) onClose(); } catch (exception) { if (isCurrentEditorSubmission(submissionSession, editorSession.current, visibleRef.current)) setError(apiError(exception)); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><KeyboardAvoidingView style={styles.backdrop} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={insets.top}><View style={[styles.sheet, { paddingBottom: insets.bottom + spacing.md, paddingLeft: insets.left + spacing.lg, paddingRight: insets.right + spacing.lg }]}><View style={styles.header}><View style={styles.headerCopy}><Text numberOfLines={1} style={styles.title}>{goal ? 'Editar meta' : 'Nueva meta'}</Text><Text numberOfLines={2} style={styles.copy}>Define un objetivo y sigue su progreso.</Text></View><Pressable disabled={saving} onPress={close} style={({ pressed }) => [styles.close, saving && styles.disabled, pressed && !saving && styles.pressed]}><Icon name="close" /></Pressable></View><ScrollView contentContainerStyle={[styles.form, { paddingBottom: insets.bottom + spacing.lg }]} keyboardDismissMode={Platform.OS === 'ios' ? 'interactive' : 'on-drag'} keyboardShouldPersistTaps="handled"><Field label="Nombre de la meta" value={values.name} onChangeText={(value) => set('name', value)} placeholder="Ej. Vacaciones" editable={!saving} /><Field label="Objetivo total" value={values.targetAmount} onChangeText={(value) => set('targetAmount', value)} placeholder="0" numeric editable={!saving} /><Field label="Ahorro inicial" value={values.currentAmount} onChangeText={(value) => set('currentAmount', value)} placeholder="0" numeric editable={!saving} /><Field label="Fecha objetivo" value={values.targetDate} onChangeText={(value) => set('targetDate', value)} placeholder="AAAA-MM-DD" editable={!saving} />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton onPress={() => void save()} loading={saving} icon="target">Guardar meta</PrimaryButton></ScrollView></View></KeyboardAvoidingView></Modal>;
}

export function ContributionEditor({ visible, goal, onClose }: { visible: boolean; goal: Goal | null; onClose: () => void }) {
  const mutations = useGoalMutations(); const insets = useSafeAreaInsets(); const contributionSession = useRef(0); const visibleRef = useRef(visible); const [amount, setAmount] = useState(''); const [error, setError] = useState(''); useEffect(() => { visibleRef.current = visible; if (visible) { contributionSession.current += 1; setAmount(''); setError(''); } return () => { contributionSession.current += 1; visibleRef.current = false; }; }, [visible, goal]);
  const saving = mutations.contribute.isPending; const close = () => { if (!saving) onClose(); };
  const save = async () => { if (saving) return; const payload = buildContributionPayload(amount); if (!goal || !Number.isFinite(payload.amount) || payload.amount <= 0) { setError('Ingresa un monto válido.'); return; } const submissionSession = contributionSession.current; try { await mutations.contribute.mutateAsync({ id: goal.id, amount: payload.amount }); if (isCurrentEditorSubmission(submissionSession, contributionSession.current, visibleRef.current)) onClose(); } catch (exception) { if (isCurrentEditorSubmission(submissionSession, contributionSession.current, visibleRef.current)) setError(apiError(exception)); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><KeyboardAvoidingView style={styles.backdrop} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={insets.top}><View style={[styles.sheet, { paddingBottom: insets.bottom + spacing.md, paddingLeft: insets.left + spacing.lg, paddingRight: insets.right + spacing.lg }]}><View style={styles.header}><View style={styles.headerCopy}><Text numberOfLines={1} style={styles.title}>Abonar a meta</Text><Text numberOfLines={2} style={styles.copy}>{goal?.name ?? ''}</Text></View><Pressable disabled={saving} onPress={close} style={({ pressed }) => [styles.close, saving && styles.disabled, pressed && !saving && styles.pressed]}><Icon name="close" /></Pressable></View><ScrollView contentContainerStyle={[styles.form, { paddingBottom: insets.bottom + spacing.lg }]} keyboardDismissMode={Platform.OS === 'ios' ? 'interactive' : 'on-drag'} keyboardShouldPersistTaps="handled"><Field label="Monto a abonar" value={amount} onChangeText={setAmount} placeholder="0" numeric editable={!saving} />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton onPress={() => void save()} loading={saving} icon="plus">Registrar aporte</PrimaryButton></ScrollView></View></KeyboardAvoidingView></Modal>;
}

function Field({ label, value, onChangeText, placeholder, numeric, editable = true }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; numeric?: boolean; editable?: boolean }) { return <View style={{ gap: 6 }}><Text style={styles.label}>{label}</Text><TextInput editable={editable} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.meta} selectionColor={colors.accent} keyboardType={numeric ? 'decimal-pad' : 'default'} style={styles.input} /></View>; }
export function confirmDeleteGoal(onConfirm: () => void) { Alert.alert('Eliminar meta', 'Esta acción no se puede deshacer.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: onConfirm }]); }

const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(49,48,46,.35)' }, sheet: { maxHeight: '90%', paddingVertical: spacing.lg, backgroundColor: colors.background, borderTopLeftRadius: 22, borderTopRightRadius: 22 }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md }, headerCopy: { flex: 1, minWidth: 0 }, title: { color: colors.text, fontSize: 22, fontWeight: '800' }, copy: { color: colors.muted, marginTop: 5 }, close: { flexShrink: 0, width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, backgroundColor: colors.surface }, disabled: { opacity: .55 }, pressed: { opacity: .82, transform: [{ scale: .97 }] }, form: { gap: 12, paddingTop: spacing.lg }, label: { color: colors.text, fontSize: 13, fontWeight: '700' }, input: { minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, paddingHorizontal: 12, color: colors.text, fontSize: 16 }, error: { color: colors.danger, fontSize: 13 }, });
